### ISSUE TITLE
Objectives and wiki

### ISSUE THREAD

**Issue by andramil** [raGan262/Quester#65]
I'm rlly sorry if this is not place to write sth like that, but I dont know where to find help. 

Item OBJ looks like:
/q obj add item id number enchantment (-q)
and I dont know what this -q means. When i added obj with it and had items (10 lava buckets) in inventory I couldnt finish my quest. Without it work great. 
Wiki is for 0.6.3 version and i dont know wehere i can find 1.0.1 wiki ;/

**Comment by raGan262** [comment]
It means that objective will require quest items instead of regular items. Quest items are like regular items, just with "Quest Item" at the top or the bottom of their lore. One way to obtain such items is by using item event created with the same command flag. (-q)

Edit: there is no 0.7+ wiki. I meant to create one but it got pushed away and now it's not worth it, because quester 2 would deprecate it anyway. (There is no quester 2 release yet and I don't know how long it will take. It will also be for sponge.)
